"""user_table

Revision ID: 95b4e63fa22d
Revises: 
Create Date: 2022-12-22 18:55:32.034408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b4e63fa22d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patiente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ci', sa.Integer(), nullable=False),
    sa.Column('down', sa.Boolean(), nullable=True),
    sa.Column('jobRecord', sa.Integer(), nullable=True),
    sa.Column('jobZone', sa.String(length=64), nullable=True),
    sa.Column('ocupCategory', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('skinColor', sa.String(length=1), nullable=True),
    sa.Column('educLevel', sa.String(length=64), nullable=True),
    sa.Column('cellphone', sa.String(length=12), nullable=True),
    sa.Column('street', sa.String(length=64), nullable=True),
    sa.Column('between', sa.String(length=64), nullable=True),
    sa.Column('neighborhood', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('apt_number', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('municipality', sa.String(length=64), nullable=True),
    sa.Column('edadGroup', sa.Integer(), nullable=True),
    sa.Column('factorGroup', sa.Integer(), nullable=True),
    sa.Column('donor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'ci')
    )
    with op.batch_alter_table('patiente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patiente_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_apt_number'), ['apt_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_between'), ['between'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_cellphone'), ['cellphone'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_donor'), ['donor'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_down'), ['down'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_edadGroup'), ['edadGroup'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_educLevel'), ['educLevel'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_factorGroup'), ['factorGroup'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_firstname'), ['firstname'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_jobRecord'), ['jobRecord'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_jobZone'), ['jobZone'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_lastname'), ['lastname'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_municipality'), ['municipality'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_neighborhood'), ['neighborhood'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_ocupCategory'), ['ocupCategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_province'), ['province'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_sex'), ['sex'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_skinColor'), ['skinColor'], unique=False)
        batch_op.create_index(batch_op.f('ix_patiente_street'), ['street'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('arterial_tension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('TAS', sa.Float(), nullable=True),
    sa.Column('TDH', sa.Float(), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arterial_tension', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arterial_tension_TAS'), ['TAS'], unique=False)
        batch_op.create_index(batch_op.f('ix_arterial_tension_TDH'), ['TDH'], unique=False)
        batch_op.create_index(batch_op.f('ix_arterial_tension_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_arterial_tension_position'), ['position'], unique=False)

    op.create_table('body_examn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('kgWeight', sa.Float(), nullable=True),
    sa.Column('sizeInM', sa.Float(), nullable=True),
    sa.Column('IMC', sa.Float(), nullable=True),
    sa.Column('general', sa.String(length=64), nullable=True),
    sa.Column('regional', sa.String(length=64), nullable=True),
    sa.Column('thyroid', sa.String(length=64), nullable=True),
    sa.Column('brest', sa.String(length=64), nullable=True),
    sa.Column('interrrogation', sa.String(length=64), nullable=True),
    sa.Column('respiratory', sa.String(length=64), nullable=True),
    sa.Column('cardiovasculary', sa.String(length=64), nullable=True),
    sa.Column('digestive', sa.String(length=64), nullable=True),
    sa.Column('rectal', sa.String(length=64), nullable=True),
    sa.Column('TAS', sa.Float(), nullable=True),
    sa.Column('TAD', sa.Float(), nullable=True),
    sa.Column('SArtPerfi', sa.String(length=64), nullable=True),
    sa.Column('SVenPerif', sa.String(length=64), nullable=True),
    sa.Column('hemalinfopoyetic', sa.String(length=64), nullable=True),
    sa.Column('genitourin_mas', sa.String(length=64), nullable=True),
    sa.Column('osteomioarticular', sa.String(length=64), nullable=True),
    sa.Column('scapularGirdleUperLimbs', sa.String(length=64), nullable=True),
    sa.Column('pelvicGirdleLowerLimbs', sa.String(length=64), nullable=True),
    sa.Column('spine', sa.String(length=64), nullable=True),
    sa.Column('neurologicStats', sa.String(length=64), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_examn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_examn_IMC'), ['IMC'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_SArtPerfi'), ['SArtPerfi'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_SVenPerif'), ['SVenPerif'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_TAD'), ['TAD'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_TAS'), ['TAS'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_brest'), ['brest'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_cardiovasculary'), ['cardiovasculary'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_digestive'), ['digestive'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_general'), ['general'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_genitourin_mas'), ['genitourin_mas'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_hemalinfopoyetic'), ['hemalinfopoyetic'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_interrrogation'), ['interrrogation'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_kgWeight'), ['kgWeight'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_neurologicStats'), ['neurologicStats'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_osteomioarticular'), ['osteomioarticular'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_pelvicGirdleLowerLimbs'), ['pelvicGirdleLowerLimbs'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_rectal'), ['rectal'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_regional'), ['regional'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_respiratory'), ['respiratory'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_scapularGirdleUperLimbs'), ['scapularGirdleUperLimbs'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_sizeInM'), ['sizeInM'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_spine'), ['spine'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_examn_thyroid'), ['thyroid'], unique=False)

    op.create_table('charge_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('consultationReason', sa.String(length=64), nullable=True),
    sa.Column('diagnostic', sa.String(length=64), nullable=True),
    sa.Column('reaction', sa.String(length=64), nullable=True),
    sa.Column('indicatedDrugs', sa.String(length=64), nullable=True),
    sa.Column('evolution', sa.String(length=200), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charge_sheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_sheet_consultationReason'), ['consultationReason'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_sheet_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_sheet_diagnostic'), ['diagnostic'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_sheet_evolution'), ['evolution'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_sheet_indicatedDrugs'), ['indicatedDrugs'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_sheet_reaction'), ['reaction'], unique=False)

    op.create_table('complementary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('Hb', sa.Float(), nullable=True),
    sa.Column('Hto', sa.Float(), nullable=True),
    sa.Column('Leuco', sa.Float(), nullable=True),
    sa.Column('VSG', sa.Float(), nullable=True),
    sa.Column('peripheralLamina', sa.String(length=64), nullable=True),
    sa.Column('HDL', sa.String(length=64), nullable=True),
    sa.Column('Glicemy', sa.String(length=64), nullable=True),
    sa.Column('Creatimia', sa.String(length=64), nullable=True),
    sa.Column('AcUrico', sa.String(length=64), nullable=True),
    sa.Column('LDH', sa.String(length=64), nullable=True),
    sa.Column('TGP', sa.String(length=64), nullable=True),
    sa.Column('TGO', sa.String(length=64), nullable=True),
    sa.Column('T4', sa.String(length=64), nullable=True),
    sa.Column('colesterol', sa.String(length=64), nullable=True),
    sa.Column('triglicrids', sa.String(length=64), nullable=True),
    sa.Column('T3', sa.String(length=64), nullable=True),
    sa.Column('TSH', sa.String(length=64), nullable=True),
    sa.Column('PSA', sa.String(length=64), nullable=True),
    sa.Column('colinesterasa', sa.String(length=64), nullable=True),
    sa.Column('plomo', sa.String(length=64), nullable=True),
    sa.Column('corpocultivo', sa.String(length=64), nullable=True),
    sa.Column('exudados', sa.String(length=64), nullable=True),
    sa.Column('fecalHeces', sa.String(length=64), nullable=True),
    sa.Column('VIH', sa.String(length=64), nullable=True),
    sa.Column('VIHDate', sa.Date(), nullable=True),
    sa.Column('VIHResult', sa.Boolean(), nullable=True),
    sa.Column('Sifilis', sa.String(length=64), nullable=True),
    sa.Column('SifilisDate', sa.Date(), nullable=True),
    sa.Column('SifilisResult', sa.Boolean(), nullable=True),
    sa.Column('BHepatitis', sa.String(length=64), nullable=True),
    sa.Column('BHepatitisDate', sa.Date(), nullable=True),
    sa.Column('BHepatitisResult', sa.Boolean(), nullable=True),
    sa.Column('CHepatitis', sa.String(length=64), nullable=True),
    sa.Column('CHepatitisDate', sa.Date(), nullable=True),
    sa.Column('CHepatitisResult', sa.Boolean(), nullable=True),
    sa.Column('adiometricaTest', sa.String(length=64), nullable=True),
    sa.Column('Rx', sa.String(length=64), nullable=True),
    sa.Column('EKG', sa.String(length=64), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complementary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complementary_AcUrico'), ['AcUrico'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_BHepatitis'), ['BHepatitis'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_BHepatitisDate'), ['BHepatitisDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_BHepatitisResult'), ['BHepatitisResult'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_CHepatitis'), ['CHepatitis'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_CHepatitisDate'), ['CHepatitisDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_CHepatitisResult'), ['CHepatitisResult'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_Creatimia'), ['Creatimia'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_EKG'), ['EKG'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_Glicemy'), ['Glicemy'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_HDL'), ['HDL'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_Hb'), ['Hb'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_Hto'), ['Hto'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_LDH'), ['LDH'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_Leuco'), ['Leuco'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_PSA'), ['PSA'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_Rx'), ['Rx'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_Sifilis'), ['Sifilis'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_SifilisDate'), ['SifilisDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_SifilisResult'), ['SifilisResult'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_T3'), ['T3'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_T4'), ['T4'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_TGO'), ['TGO'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_TGP'), ['TGP'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_TSH'), ['TSH'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_VIH'), ['VIH'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_VIHDate'), ['VIHDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_VIHResult'), ['VIHResult'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_VSG'), ['VSG'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_adiometricaTest'), ['adiometricaTest'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_colesterol'), ['colesterol'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_colinesterasa'), ['colinesterasa'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_corpocultivo'), ['corpocultivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_exudados'), ['exudados'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_fecalHeces'), ['fecalHeces'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_peripheralLamina'), ['peripheralLamina'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_plomo'), ['plomo'], unique=False)
        batch_op.create_index(batch_op.f('ix_complementary_triglicrids'), ['triglicrids'], unique=False)

    op.create_table('cronics_ilness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('ilness', sa.String(length=20), nullable=True),
    sa.Column('anothers', sa.String(length=64), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cronics_ilness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cronics_ilness_anothers'), ['anothers'], unique=False)
        batch_op.create_index(batch_op.f('ix_cronics_ilness_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cronics_ilness_ilness'), ['ilness'], unique=False)

    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_date'), ['date'], unique=False)

    op.create_table('exposition_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('risks', sa.String(length=17), nullable=True),
    sa.Column('anothers', sa.String(length=64), nullable=True),
    sa.Column('non_ionazinRadiations', sa.String(length=4), nullable=True),
    sa.Column('ionazingRadiations', sa.String(length=6), nullable=True),
    sa.Column('expRadiometricEvaluation', sa.String(length=1), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exposition_risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exposition_risks_anothers'), ['anothers'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposition_risks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposition_risks_expRadiometricEvaluation'), ['expRadiometricEvaluation'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposition_risks_ionazingRadiations'), ['ionazingRadiations'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposition_risks_non_ionazinRadiations'), ['non_ionazinRadiations'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposition_risks_risks'), ['risks'], unique=False)

    op.create_table('genetics_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('risks', sa.String(length=4), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genetics_risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genetics_risks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_genetics_risks_risks'), ['risks'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('casualEvent', sa.String(length=64), nullable=True),
    sa.Column('accident', sa.Boolean(), nullable=True),
    sa.Column('accidentProperties', sa.String(length=64), nullable=True),
    sa.Column('medicalCerificated', sa.String(length=64), nullable=True),
    sa.Column('indicatedBy', sa.String(length=64), nullable=True),
    sa.Column('medicalCerificatedSince', sa.Date(), nullable=True),
    sa.Column('medicalCerificatedTo', sa.Date(), nullable=True),
    sa.Column('medicalcertificatedCauses', sa.String(length=64), nullable=True),
    sa.Column('medicalCertificatedFrom', sa.String(length=64), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_accident'), ['accident'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_accidentProperties'), ['accidentProperties'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_casualEvent'), ['casualEvent'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_indicatedBy'), ['indicatedBy'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_medicalCerificated'), ['medicalCerificated'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_medicalCerificatedSince'), ['medicalCerificatedSince'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_medicalCerificatedTo'), ['medicalCerificatedTo'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_medicalCertificatedFrom'), ['medicalCertificatedFrom'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_medicalcertificatedCauses'), ['medicalcertificatedCauses'], unique=False)

    op.create_table('initial_health_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drugAlergy', sa.String(length=64), nullable=True),
    sa.Column('tetanusVaccionelastActivation', sa.Date(), nullable=True),
    sa.Column('tetanusVaccionenextActivation', sa.Date(), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('initial_health_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_initial_health_state_drugAlergy'), ['drugAlergy'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_health_state_tetanusVaccionelastActivation'), ['tetanusVaccionelastActivation'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_health_state_tetanusVaccionenextActivation'), ['tetanusVaccionenextActivation'], unique=False)

    op.create_table('initial_sanitary_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('outside', sa.Boolean(), nullable=True),
    sa.Column('departureDate', sa.Date(), nullable=True),
    sa.Column('arrivalDate', sa.Date(), nullable=True),
    sa.Column('returnControl', sa.Boolean(), nullable=True),
    sa.Column('returnControlDate', sa.Date(), nullable=True),
    sa.Column('controls', sa.String(length=6), nullable=True),
    sa.Column('return3MonthControl', sa.Boolean(), nullable=True),
    sa.Column('returneMothControlDate', sa.Date(), nullable=True),
    sa.Column('controls3Month', sa.String(length=6), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('initial_sanitary_control', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_arrivalDate'), ['arrivalDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_controls'), ['controls'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_controls3Month'), ['controls3Month'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_departureDate'), ['departureDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_outside'), ['outside'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_return3MonthControl'), ['return3MonthControl'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_returnControl'), ['returnControl'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_returnControlDate'), ['returnControlDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_sanitary_control_returneMothControlDate'), ['returneMothControlDate'], unique=False)

    op.create_table('medic_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pathologicalInterest', sa.String(length=64), nullable=True),
    sa.Column('laboralInterestRisks', sa.String(length=64), nullable=True),
    sa.Column('correctivesActions', sa.String(length=64), nullable=True),
    sa.Column('individualProtection', sa.String(length=64), nullable=True),
    sa.Column('nutricionalEvaluation', sa.String(length=64), nullable=True),
    sa.Column('complementaryResume', sa.String(length=64), nullable=True),
    sa.Column('bodyStateResume', sa.String(length=64), nullable=True),
    sa.Column('DispensarialResume', sa.String(length=64), nullable=True),
    sa.Column('extra', sa.String(length=64), nullable=True),
    sa.Column('suitable', sa.String(length=64), nullable=True),
    sa.Column('correctiveAction', sa.String(length=64), nullable=True),
    sa.Column('nextMedicCheck', sa.Date(), nullable=True),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medic_check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medic_check_DispensarialResume'), ['DispensarialResume'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_bodyStateResume'), ['bodyStateResume'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_check'), ['check'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_complementaryResume'), ['complementaryResume'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_correctiveAction'), ['correctiveAction'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_correctivesActions'), ['correctivesActions'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_extra'), ['extra'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_individualProtection'), ['individualProtection'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_laboralInterestRisks'), ['laboralInterestRisks'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_nextMedicCheck'), ['nextMedicCheck'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_nutricionalEvaluation'), ['nutricionalEvaluation'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_pathologicalInterest'), ['pathologicalInterest'], unique=False)
        batch_op.create_index(batch_op.f('ix_medic_check_suitable'), ['suitable'], unique=False)

    op.create_table('ocupational_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('previousOccupation', sa.String(length=64), nullable=True),
    sa.Column('exposedTo', sa.String(length=64), nullable=True),
    sa.Column('exposedToInTime', sa.String(length=64), nullable=True),
    sa.Column('currentOccupation', sa.String(length=64), nullable=True),
    sa.Column('currentOccupationSince', sa.Date(), nullable=True),
    sa.Column('currentOccupationTo', sa.Date(), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocupational_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocupational_history_currentOccupation'), ['currentOccupation'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocupational_history_currentOccupationSince'), ['currentOccupationSince'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocupational_history_currentOccupationTo'), ['currentOccupationTo'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocupational_history_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocupational_history_exposedTo'), ['exposedTo'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocupational_history_exposedToInTime'), ['exposedToInTime'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocupational_history_previousOccupation'), ['previousOccupation'], unique=False)

    op.create_table('pathological_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathologies', sa.String(length=20), nullable=True),
    sa.Column('othersPathologies', sa.String(length=64), nullable=True),
    sa.Column('professionalIlness', sa.String(length=64), nullable=True),
    sa.Column('surgeries', sa.String(length=64), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pathological_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pathological_history_othersPathologies'), ['othersPathologies'], unique=False)
        batch_op.create_index(batch_op.f('ix_pathological_history_pathologies'), ['pathologies'], unique=False)
        batch_op.create_index(batch_op.f('ix_pathological_history_professionalIlness'), ['professionalIlness'], unique=False)
        batch_op.create_index(batch_op.f('ix_pathological_history_surgeries'), ['surgeries'], unique=False)

    op.create_table('psicological',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('workFeelings', sa.String(length=64), nullable=True),
    sa.Column('stressLevel', sa.String(length=64), nullable=True),
    sa.Column('symptoms', sa.String(length=64), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psicological', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psicological_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_psicological_stressLevel'), ['stressLevel'], unique=False)
        batch_op.create_index(batch_op.f('ix_psicological_symptoms'), ['symptoms'], unique=False)
        batch_op.create_index(batch_op.f('ix_psicological_workFeelings'), ['workFeelings'], unique=False)

    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dispensaryGroup', sa.String(length=64), nullable=True),
    sa.Column('valoration', sa.String(length=200), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_dispensaryGroup'), ['dispensaryGroup'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_valoration'), ['valoration'], unique=False)

    op.create_table('vacunation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaccines', sa.String(length=11), nullable=True),
    sa.Column('anothers', sa.String(length=64), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacunation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacunation_anothers'), ['anothers'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacunation_vaccines'), ['vaccines'], unique=False)

    op.create_table('vision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('evaluationCenter', sa.String(length=64), nullable=True),
    sa.Column('OD', sa.String(length=64), nullable=True),
    sa.Column('OI', sa.String(length=64), nullable=True),
    sa.Column('results', sa.String(length=64), nullable=True),
    sa.Column('diagnostic', sa.String(length=64), nullable=True),
    sa.Column('patiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patiente_id'], ['patiente.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_OD'), ['OD'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_OI'), ['OI'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_diagnostic'), ['diagnostic'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_evaluationCenter'), ['evaluationCenter'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_results'), ['results'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_results'))
        batch_op.drop_index(batch_op.f('ix_vision_evaluationCenter'))
        batch_op.drop_index(batch_op.f('ix_vision_diagnostic'))
        batch_op.drop_index(batch_op.f('ix_vision_date'))
        batch_op.drop_index(batch_op.f('ix_vision_OI'))
        batch_op.drop_index(batch_op.f('ix_vision_OD'))

    op.drop_table('vision')
    with op.batch_alter_table('vacunation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacunation_vaccines'))
        batch_op.drop_index(batch_op.f('ix_vacunation_anothers'))

    op.drop_table('vacunation')
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_valoration'))
        batch_op.drop_index(batch_op.f('ix_resume_dispensaryGroup'))
        batch_op.drop_index(batch_op.f('ix_resume_date'))

    op.drop_table('resume')
    with op.batch_alter_table('psicological', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psicological_workFeelings'))
        batch_op.drop_index(batch_op.f('ix_psicological_symptoms'))
        batch_op.drop_index(batch_op.f('ix_psicological_stressLevel'))
        batch_op.drop_index(batch_op.f('ix_psicological_date'))

    op.drop_table('psicological')
    with op.batch_alter_table('pathological_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pathological_history_surgeries'))
        batch_op.drop_index(batch_op.f('ix_pathological_history_professionalIlness'))
        batch_op.drop_index(batch_op.f('ix_pathological_history_pathologies'))
        batch_op.drop_index(batch_op.f('ix_pathological_history_othersPathologies'))

    op.drop_table('pathological_history')
    with op.batch_alter_table('ocupational_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocupational_history_previousOccupation'))
        batch_op.drop_index(batch_op.f('ix_ocupational_history_exposedToInTime'))
        batch_op.drop_index(batch_op.f('ix_ocupational_history_exposedTo'))
        batch_op.drop_index(batch_op.f('ix_ocupational_history_date'))
        batch_op.drop_index(batch_op.f('ix_ocupational_history_currentOccupationTo'))
        batch_op.drop_index(batch_op.f('ix_ocupational_history_currentOccupationSince'))
        batch_op.drop_index(batch_op.f('ix_ocupational_history_currentOccupation'))

    op.drop_table('ocupational_history')
    with op.batch_alter_table('medic_check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medic_check_suitable'))
        batch_op.drop_index(batch_op.f('ix_medic_check_pathologicalInterest'))
        batch_op.drop_index(batch_op.f('ix_medic_check_nutricionalEvaluation'))
        batch_op.drop_index(batch_op.f('ix_medic_check_nextMedicCheck'))
        batch_op.drop_index(batch_op.f('ix_medic_check_laboralInterestRisks'))
        batch_op.drop_index(batch_op.f('ix_medic_check_individualProtection'))
        batch_op.drop_index(batch_op.f('ix_medic_check_extra'))
        batch_op.drop_index(batch_op.f('ix_medic_check_date'))
        batch_op.drop_index(batch_op.f('ix_medic_check_correctivesActions'))
        batch_op.drop_index(batch_op.f('ix_medic_check_correctiveAction'))
        batch_op.drop_index(batch_op.f('ix_medic_check_complementaryResume'))
        batch_op.drop_index(batch_op.f('ix_medic_check_check'))
        batch_op.drop_index(batch_op.f('ix_medic_check_bodyStateResume'))
        batch_op.drop_index(batch_op.f('ix_medic_check_DispensarialResume'))

    op.drop_table('medic_check')
    with op.batch_alter_table('initial_sanitary_control', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_returneMothControlDate'))
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_returnControlDate'))
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_returnControl'))
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_return3MonthControl'))
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_outside'))
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_departureDate'))
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_country'))
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_controls3Month'))
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_controls'))
        batch_op.drop_index(batch_op.f('ix_initial_sanitary_control_arrivalDate'))

    op.drop_table('initial_sanitary_control')
    with op.batch_alter_table('initial_health_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_initial_health_state_tetanusVaccionenextActivation'))
        batch_op.drop_index(batch_op.f('ix_initial_health_state_tetanusVaccionelastActivation'))
        batch_op.drop_index(batch_op.f('ix_initial_health_state_drugAlergy'))

    op.drop_table('initial_health_state')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_medicalcertificatedCauses'))
        batch_op.drop_index(batch_op.f('ix_incidents_medicalCertificatedFrom'))
        batch_op.drop_index(batch_op.f('ix_incidents_medicalCerificatedTo'))
        batch_op.drop_index(batch_op.f('ix_incidents_medicalCerificatedSince'))
        batch_op.drop_index(batch_op.f('ix_incidents_medicalCerificated'))
        batch_op.drop_index(batch_op.f('ix_incidents_indicatedBy'))
        batch_op.drop_index(batch_op.f('ix_incidents_date'))
        batch_op.drop_index(batch_op.f('ix_incidents_casualEvent'))
        batch_op.drop_index(batch_op.f('ix_incidents_accidentProperties'))
        batch_op.drop_index(batch_op.f('ix_incidents_accident'))

    op.drop_table('incidents')
    with op.batch_alter_table('genetics_risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genetics_risks_risks'))
        batch_op.drop_index(batch_op.f('ix_genetics_risks_date'))

    op.drop_table('genetics_risks')
    with op.batch_alter_table('exposition_risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exposition_risks_risks'))
        batch_op.drop_index(batch_op.f('ix_exposition_risks_non_ionazinRadiations'))
        batch_op.drop_index(batch_op.f('ix_exposition_risks_ionazingRadiations'))
        batch_op.drop_index(batch_op.f('ix_exposition_risks_expRadiometricEvaluation'))
        batch_op.drop_index(batch_op.f('ix_exposition_risks_date'))
        batch_op.drop_index(batch_op.f('ix_exposition_risks_anothers'))

    op.drop_table('exposition_risks')
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_date'))

    op.drop_table('donor')
    with op.batch_alter_table('cronics_ilness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cronics_ilness_ilness'))
        batch_op.drop_index(batch_op.f('ix_cronics_ilness_date'))
        batch_op.drop_index(batch_op.f('ix_cronics_ilness_anothers'))

    op.drop_table('cronics_ilness')
    with op.batch_alter_table('complementary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complementary_triglicrids'))
        batch_op.drop_index(batch_op.f('ix_complementary_plomo'))
        batch_op.drop_index(batch_op.f('ix_complementary_peripheralLamina'))
        batch_op.drop_index(batch_op.f('ix_complementary_fecalHeces'))
        batch_op.drop_index(batch_op.f('ix_complementary_exudados'))
        batch_op.drop_index(batch_op.f('ix_complementary_date'))
        batch_op.drop_index(batch_op.f('ix_complementary_corpocultivo'))
        batch_op.drop_index(batch_op.f('ix_complementary_colinesterasa'))
        batch_op.drop_index(batch_op.f('ix_complementary_colesterol'))
        batch_op.drop_index(batch_op.f('ix_complementary_adiometricaTest'))
        batch_op.drop_index(batch_op.f('ix_complementary_VSG'))
        batch_op.drop_index(batch_op.f('ix_complementary_VIHResult'))
        batch_op.drop_index(batch_op.f('ix_complementary_VIHDate'))
        batch_op.drop_index(batch_op.f('ix_complementary_VIH'))
        batch_op.drop_index(batch_op.f('ix_complementary_TSH'))
        batch_op.drop_index(batch_op.f('ix_complementary_TGP'))
        batch_op.drop_index(batch_op.f('ix_complementary_TGO'))
        batch_op.drop_index(batch_op.f('ix_complementary_T4'))
        batch_op.drop_index(batch_op.f('ix_complementary_T3'))
        batch_op.drop_index(batch_op.f('ix_complementary_SifilisResult'))
        batch_op.drop_index(batch_op.f('ix_complementary_SifilisDate'))
        batch_op.drop_index(batch_op.f('ix_complementary_Sifilis'))
        batch_op.drop_index(batch_op.f('ix_complementary_Rx'))
        batch_op.drop_index(batch_op.f('ix_complementary_PSA'))
        batch_op.drop_index(batch_op.f('ix_complementary_Leuco'))
        batch_op.drop_index(batch_op.f('ix_complementary_LDH'))
        batch_op.drop_index(batch_op.f('ix_complementary_Hto'))
        batch_op.drop_index(batch_op.f('ix_complementary_Hb'))
        batch_op.drop_index(batch_op.f('ix_complementary_HDL'))
        batch_op.drop_index(batch_op.f('ix_complementary_Glicemy'))
        batch_op.drop_index(batch_op.f('ix_complementary_EKG'))
        batch_op.drop_index(batch_op.f('ix_complementary_Creatimia'))
        batch_op.drop_index(batch_op.f('ix_complementary_CHepatitisResult'))
        batch_op.drop_index(batch_op.f('ix_complementary_CHepatitisDate'))
        batch_op.drop_index(batch_op.f('ix_complementary_CHepatitis'))
        batch_op.drop_index(batch_op.f('ix_complementary_BHepatitisResult'))
        batch_op.drop_index(batch_op.f('ix_complementary_BHepatitisDate'))
        batch_op.drop_index(batch_op.f('ix_complementary_BHepatitis'))
        batch_op.drop_index(batch_op.f('ix_complementary_AcUrico'))

    op.drop_table('complementary')
    with op.batch_alter_table('charge_sheet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_sheet_reaction'))
        batch_op.drop_index(batch_op.f('ix_charge_sheet_indicatedDrugs'))
        batch_op.drop_index(batch_op.f('ix_charge_sheet_evolution'))
        batch_op.drop_index(batch_op.f('ix_charge_sheet_diagnostic'))
        batch_op.drop_index(batch_op.f('ix_charge_sheet_date'))
        batch_op.drop_index(batch_op.f('ix_charge_sheet_consultationReason'))

    op.drop_table('charge_sheet')
    with op.batch_alter_table('body_examn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_examn_thyroid'))
        batch_op.drop_index(batch_op.f('ix_body_examn_spine'))
        batch_op.drop_index(batch_op.f('ix_body_examn_sizeInM'))
        batch_op.drop_index(batch_op.f('ix_body_examn_scapularGirdleUperLimbs'))
        batch_op.drop_index(batch_op.f('ix_body_examn_respiratory'))
        batch_op.drop_index(batch_op.f('ix_body_examn_regional'))
        batch_op.drop_index(batch_op.f('ix_body_examn_rectal'))
        batch_op.drop_index(batch_op.f('ix_body_examn_pelvicGirdleLowerLimbs'))
        batch_op.drop_index(batch_op.f('ix_body_examn_osteomioarticular'))
        batch_op.drop_index(batch_op.f('ix_body_examn_neurologicStats'))
        batch_op.drop_index(batch_op.f('ix_body_examn_kgWeight'))
        batch_op.drop_index(batch_op.f('ix_body_examn_interrrogation'))
        batch_op.drop_index(batch_op.f('ix_body_examn_hemalinfopoyetic'))
        batch_op.drop_index(batch_op.f('ix_body_examn_genitourin_mas'))
        batch_op.drop_index(batch_op.f('ix_body_examn_general'))
        batch_op.drop_index(batch_op.f('ix_body_examn_digestive'))
        batch_op.drop_index(batch_op.f('ix_body_examn_date'))
        batch_op.drop_index(batch_op.f('ix_body_examn_cardiovasculary'))
        batch_op.drop_index(batch_op.f('ix_body_examn_brest'))
        batch_op.drop_index(batch_op.f('ix_body_examn_TAS'))
        batch_op.drop_index(batch_op.f('ix_body_examn_TAD'))
        batch_op.drop_index(batch_op.f('ix_body_examn_SVenPerif'))
        batch_op.drop_index(batch_op.f('ix_body_examn_SArtPerfi'))
        batch_op.drop_index(batch_op.f('ix_body_examn_IMC'))

    op.drop_table('body_examn')
    with op.batch_alter_table('arterial_tension', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arterial_tension_position'))
        batch_op.drop_index(batch_op.f('ix_arterial_tension_date'))
        batch_op.drop_index(batch_op.f('ix_arterial_tension_TDH'))
        batch_op.drop_index(batch_op.f('ix_arterial_tension_TAS'))

    op.drop_table('arterial_tension')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('patiente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patiente_street'))
        batch_op.drop_index(batch_op.f('ix_patiente_skinColor'))
        batch_op.drop_index(batch_op.f('ix_patiente_sex'))
        batch_op.drop_index(batch_op.f('ix_patiente_province'))
        batch_op.drop_index(batch_op.f('ix_patiente_ocupCategory'))
        batch_op.drop_index(batch_op.f('ix_patiente_number'))
        batch_op.drop_index(batch_op.f('ix_patiente_neighborhood'))
        batch_op.drop_index(batch_op.f('ix_patiente_municipality'))
        batch_op.drop_index(batch_op.f('ix_patiente_lastname'))
        batch_op.drop_index(batch_op.f('ix_patiente_jobZone'))
        batch_op.drop_index(batch_op.f('ix_patiente_jobRecord'))
        batch_op.drop_index(batch_op.f('ix_patiente_firstname'))
        batch_op.drop_index(batch_op.f('ix_patiente_factorGroup'))
        batch_op.drop_index(batch_op.f('ix_patiente_educLevel'))
        batch_op.drop_index(batch_op.f('ix_patiente_edadGroup'))
        batch_op.drop_index(batch_op.f('ix_patiente_down'))
        batch_op.drop_index(batch_op.f('ix_patiente_donor'))
        batch_op.drop_index(batch_op.f('ix_patiente_date'))
        batch_op.drop_index(batch_op.f('ix_patiente_cellphone'))
        batch_op.drop_index(batch_op.f('ix_patiente_between'))
        batch_op.drop_index(batch_op.f('ix_patiente_apt_number'))
        batch_op.drop_index(batch_op.f('ix_patiente_age'))

    op.drop_table('patiente')
    # ### end Alembic commands ###
